name: Docker test

on:
  push:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: enable qemu for arm
      run: sudo apt-get install -y qemu-user-static
    - run: sudo mkdir -p /etc/binfmt.d
    - run: sudo cp qemu-arm-static.conf /etc/binfmt.d
    - run: sudo systemctl restart systemd-binfmt
    - name: docker
      run: docker run --rm -i -v /usr/bin/qemu-arm-static:/usr/bin/qemu-arm-static hoertech/docker-buildenv:liblsl_armv7-linux-gcc-7 /bin/date
