name: Docker test

on:
  push:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: enable qemu for arm
      run: sudo apt-get install -y qemu-user-static
    - run: sudo systemctl status binfmt-support.service
    - name: docker
      run: docker run --rm hoertech/docker-buildenv:liblsl_armv7-linux-gcc-7 uname -a
      